import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import localfont from 'next/font/local';
import NavbarLogin from './userHome/_components/navbarlogin';

const inter = Inter({ subsets: ['latin'] });

const positiveForward = localfont({
  src: [
    {
      path: '../../public/fonts/PositiveForward.otf',
      weight: '700',
    },
  ],
  variable: '--font-positiveForward',
});

export const metadata: Metadata = {
  title: 'TICKET ZONE',
  description: 'Generated by TICKET ZONE',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${positiveForward.variable}`}>
      <body className={inter.className}>
        {children}</body>
    </html>
  );
}
